// <auto-generated />
using System;
using EventAggregator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventAggregator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528191942_AddIsBanned")]
    partial class AddIsBanned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EventAggregator.API.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxPeople")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedSourceId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventAggregator.API.Models.FeedSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedSources");
                });

            modelBuilder.Entity("EventAggregator.API.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchKeyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("EventAggregator.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReportSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventAggregator.API.Models.UserEventStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInCalendar")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEventStatuses");
                });

            modelBuilder.Entity("EventAggregator.API.Models.UserFilter", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "FilterId");

                    b.HasIndex("FilterId");

                    b.ToTable("UserFilters");
                });

            modelBuilder.Entity("EventAggregator.API.Models.Event", b =>
                {
                    b.HasOne("EventAggregator.API.Models.FeedSource", "FeedSource")
                        .WithMany("Events")
                        .HasForeignKey("FeedSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeedSource");
                });

            modelBuilder.Entity("EventAggregator.API.Models.UserEventStatus", b =>
                {
                    b.HasOne("EventAggregator.API.Models.Event", "Event")
                        .WithMany("UserEventStatuses")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventAggregator.API.Models.User", "User")
                        .WithMany("UserEventStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventAggregator.API.Models.UserFilter", b =>
                {
                    b.HasOne("EventAggregator.API.Models.Filter", "Filter")
                        .WithMany("UserFilters")
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventAggregator.API.Models.User", "User")
                        .WithMany("UserFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventAggregator.API.Models.Event", b =>
                {
                    b.Navigation("UserEventStatuses");
                });

            modelBuilder.Entity("EventAggregator.API.Models.FeedSource", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventAggregator.API.Models.Filter", b =>
                {
                    b.Navigation("UserFilters");
                });

            modelBuilder.Entity("EventAggregator.API.Models.User", b =>
                {
                    b.Navigation("UserEventStatuses");

                    b.Navigation("UserFilters");
                });
#pragma warning restore 612, 618
        }
    }
}
